EVENTS = [
    {
        "name": "FUN WITH WELDING",
        "description": "Structural Design competition. Demonstrate your welding and structural design skills.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "team",
        "min_team_size": 2,
        "max_team_size": 3,
        "coordinators": ["TBD"],
        "registration_deadline": "2026-02-09T23:59:59"
    },
    {
        "name": "BRIDGE DESIGNING",
        "description": "BRIDGE ARCHITECH. Design and construct the most efficient bridge structure.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "team",
        "min_team_size": 3,
        "max_team_size": 4,
        "coordinators": ["TBD"],
    },
    {
        "name": "CIRCUIT DESIGNING",
        "description": "FUN WITH ELECTRONICS. Design and debug electronic circuits.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "team",
        "min_team_size": 2,
        "max_team_size": 2,
        "coordinators": ["TBD"],
    },
    {
        "name": "MATH OLYMPIAD",
        "description": "MATH OLYMPIA. Test your mathematical prowess.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "coordinators": ["TBD"],
    },
    {
        "name": "QUIZ",
        "description": "TECH QUIZ. A battle of wits and technical knowledge.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "team",
        "min_team_size": 2,
        "max_team_size": 3,
        "coordinators": ["TBD"],
    },
    {
        "name": "FUN WITH CODING",
        "description": "CODATHAN. Competitive coding challenge.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "coordinators": ["TBD"],
    },
    {
        "name": "JAM",
        "description": "Just A Minute. Show off your speaking skills.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "coordinators": ["TBD"],
    },
    {
        "name": "FACE PAINTING",
        "description": "FACE THEME. Colours and Paint brush to be arranged by the participants.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "team",
        "min_team_size": 2,
        "max_team_size": 2,
        "coordinators": ["TBD"],
    },
    {
        "name": "RANGOLI",
        "description": "FLOOR ART. Colours to be arranged by the participants.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "team",
        "min_team_size": 2,
        "max_team_size": 4,
        "coordinators": ["TBD"],
    },
    {
        "name": "FUN EVENTS ON STAGE",
        "description": "Outdoor Fun Events.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "coordinators": ["TBD"],
    },
    {
        "name": "POSTER PAINTING",
        "description": "DIMAG KI BATTI. Colours and Paint brush to be arranged by the participants.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "coordinators": ["TBD"],
    },
    {
        "name": "ROBOTICS",
        "description": "Robotics competition. Build and battle.",
        "sub_fest": "TECHNOLOGY-ANWESH",
        "event_type": "team",
        "min_team_size": 2,
        "max_team_size": 4,
        "coordinators": ["TBD"],
    }
]
